# Generated by Django 5.0.1 on 2024-01-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'STUDENT'), ('TH', 'TEACHER'), ('OW', 'OWNER')], default='ST'),
        ),
    ]
