# Generated by Django 5.0.1 on 2024-01-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_status',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('OWNER', 'OWNER')], default='STUDENT'),
        ),
    ]
