# Generated by Django 5.0.1 on 2024-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recordingaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
